import Header from "@/pages/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Footer from "@/pages/Footer";
import { AuthContextProvider } from "./context/AuthContext";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="main_wrapper">
        <AuthContextProvider>
          <Header />
          {children}
          <Footer />
        </AuthContextProvider>
        {/* <ToastContainer/> */}
      </body>
    </html>
  );
}
